# roles/httpd/tasks/main.yml
---

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: httpd

- include: security.yml
  tags: 
    - el7
    - security

- include: httpd.yml
  tags:
    - httpd
